#!/bin/bash

reference_results=~/Software/CitcomS/tests/automated_integration_tests

status="passed"
rm $reference_results/$1/data/*.diff

for file in `ls $reference_results/$1/reference_data/`
do 
tracer_log_file=`echo $file| grep 'tracer_log\|log\|time\|chkpt'`
if [ "$tracer_log_file" == "" ]
then
#echo "Checking file:" $file
difference=`diff $reference_results/$1/reference_data/$file $reference_results/$1/data/$file`
fi

if [ "$difference" != "" ]
then
status="failed"
diff_log_file=$reference_results/$1/data/$file.diff
echo "$Diff from `date`" > $diff_log_file
diff $reference_results/$1/data/$file $reference_results/$1/reference_data/$file >> $diff_log_file
fi

difference=""
done

echo "test $testcase $status"
#if [ "$status" != "passed" ]
#then
#echo "differences are saved in the $testcase data folder's .diff files"
#fi

