#!/bin/bash

cd `dirname $0`

reference_data=$1reference_data
test_data=$1data

status="passed"
rm $test_data/*.diff

for file in `ls $reference_data`
do 
tracer_log_file=`echo $file| grep 'tracer_log\|log\|time\|chkpt'`
if [ "$tracer_log_file" == "" ]
then
#echo "Checking file:" $file
difference=`diff $reference_data/$file $test_data/$file`
fi

if [ "$difference" != "" ]
then
status="failed"
diff_log_file=$test_data/$file.diff
echo "$Diff from `date`" > $diff_log_file
diff $reference_data/$file $test_data/$file >> $diff_log_file
fi

difference=""
done

echo "test $testcase $status"
#if [ "$status" != "passed" ]
#then
#echo "differences are saved in the $testcase data folder's .diff files"
#fi

