#!/bin/bash

reference_tests=/office/Software/Citcom-Versionen/CitcomS/tests/automated_integration_tests

echo start $1
cd $reference_tests/$1/configuration/ 
/office/Software/Citcom-Versionen/CitcomS/bin/citcoms $1.cfg
