#!/bin/bash

reference_tests=/office/Software/Citcom-Versionen/CitcomS/tests/automated_integration_tests

for testcase in `ls $reference_tests`
do
echo start $testcase
cd $reference_tests/$testcase/configuration/ 
/office/Software/Citcom-Versionen/CitcomS/bin/citcoms $testcase.cfg

done
