#!/bin/bash

reference_tests=/office/Software/Citcom-Versionen/CitcomS/tests/automated_integration_tests
cluster_home=/home/mod/rengas
cluster_tests=$cluster_home/citcom_models/tests
cluster=gmod2

for testcase in `ls $reference_tests`
do
echo start $testcase

if ssh gmod2 "[ ! -e $cluster_tests/$testcase ]"
then
ssh $cluster "mkdir $cluster_tests/$testcase"
fi

rsync -rz $reference_tests/$testcase/configuration/* $cluster:$cluster_tests/$testcase/configuration/
ssh $cluster "cd $cluster_tests/$testcase/configuration/ && $cluster_home/CitcomS/bin/citcoms $testcase.cfg"
done
